format = """
$directory\
$git_branch\
$git_status\
$python\
$rust\
$golang\
$cmd_duration\
$character"""

[gcloud]
disabled = true

[aws]
disabled = true

[azure]
disabled = true

[kubernetes]
disabled = true

[directory]
truncation_length = 3
truncate_to_repo = true

[git_branch]
format = "on [$symbol$branch]($style) "

[git_status]
format = '([$all_status$ahead_behind]($style)) '
conflicted = "conflicted "
ahead = "ahead "
behind = "behind "
diverged = "diverged "
untracked = "untracked "
stashed = "stashed "
modified = "modified "
staged = "staged "
renamed = "renamed "
deleted = "deleted "

[cmd_duration]
min_time = 2000
format = "took [$duration]($style) "

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
